#############################################################################
# Makefile for building: SamuBrain
# Generated by qmake (3.0) (Qt 5.0.2) on: Sze máj. 18 06:22:11 2016
# Project:  SamuLife.pro
# Template: app
# Command: /home/kinga/Qt5.0.2/5.0.2/gcc_64/bin/qmake -o Makefile SamuLife.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DLIFEOFGAME -DQ_LOOKUP_TABLE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -fopenmp `pkg-config --cflags opencv` `pkg-config --libs opencv` -std=c++11 -std=c++1y -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../Qt5.0.2/5.0.2/gcc_64/mkspecs/linux-g++-64 -I. -I. -I../Qt5.0.2/5.0.2/gcc_64/include -I../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets -I../Qt5.0.2/5.0.2/gcc_64/include/QtGui -I../Qt5.0.2/5.0.2/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/home/kinga/Qt5.0.2/5.0.2/gcc_64 -Wl,-rpath,/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -fopenmp `pkg-config --libs opencv` -L/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kinga/Qt5.0.2/5.0.2/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SamuLife.cpp \
		GameOfLife.cpp \
		SamuBrain.cpp moc_GameOfLife.cpp \
		moc_SamuLife.cpp
OBJECTS       = main.o \
		SamuLife.o \
		GameOfLife.o \
		SamuBrain.o \
		moc_GameOfLife.o \
		moc_SamuLife.o
DIST          = ../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/linux.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/qconfig.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/default_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/c++11.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resources.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/moc.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/uic.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/wayland-scanner.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/lex.prf \
		SamuLife.pro \
		SamuLife.pro
QMAKE_TARGET  = SamuBrain
DESTDIR       = 
TARGET        = SamuBrain


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SamuLife.pro ../Qt5.0.2/5.0.2/gcc_64/mkspecs/linux-g++-64/qmake.conf ../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/linux.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/qconfig.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/default_pre.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/c++11.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resources.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/moc.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/uic.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/wayland-scanner.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/lex.prf \
		SamuLife.pro \
		/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Widgets.prl \
		/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Gui.prl \
		/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile SamuLife.pro
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_pre.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/shell-unix.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/unix.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/linux.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-base.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/common/g++-unix.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/qconfig.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_functions.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt_config.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/linux-g++-64/qmake.conf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/spec_post.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_pre.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/default_pre.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resolve_config.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/default_post.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/c++11.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/warn_on.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/qt.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/resources.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/moc.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/uic.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/unix/thread.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/wayland-scanner.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/exceptions.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/yacc.prf:
../Qt5.0.2/5.0.2/gcc_64/mkspecs/features/lex.prf:
SamuLife.pro:
/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Widgets.prl:
/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Gui.prl:
/home/kinga/Qt5.0.2/5.0.2/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SamuLife.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SamuBrain1.0.0 || mkdir -p .tmp/SamuBrain1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SamuBrain1.0.0/ && $(COPY_FILE) --parents SamuBrain.h GameOfLife.h SamuLife.h SamuQl.h .tmp/SamuBrain1.0.0/ && $(COPY_FILE) --parents main.cpp SamuLife.cpp GameOfLife.cpp SamuBrain.cpp .tmp/SamuBrain1.0.0/ && (cd `dirname .tmp/SamuBrain1.0.0` && $(TAR) SamuBrain1.0.0.tar SamuBrain1.0.0 && $(COMPRESS) SamuBrain1.0.0.tar) && $(MOVE) `dirname .tmp/SamuBrain1.0.0`/SamuBrain1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SamuBrain1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: moc_GameOfLife.cpp moc_SamuLife.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GameOfLife.cpp moc_SamuLife.cpp
moc_GameOfLife.cpp: ../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		SamuBrain.h \
		SamuQl.h \
		GameOfLife.h
	/home/kinga/Qt5.0.2/5.0.2/gcc_64/bin/moc $(DEFINES) $(INCPATH) GameOfLife.h -o moc_GameOfLife.cpp

moc_SamuLife.cpp: ../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QKeyEvent \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qregion.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrect.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsize.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qregexp.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfile.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmargins.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpalette.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcolor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qrgb.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qbrush.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qline.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtransform.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qimage.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfont.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcursor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qicon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QPainter \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainter.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpen.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QFont \
		GameOfLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		SamuBrain.h \
		SamuQl.h \
		SamuLife.h
	/home/kinga/Qt5.0.2/5.0.2/gcc_64/bin/moc $(DEFINES) $(INCPATH) SamuLife.h -o moc_SamuLife.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/QApplication \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qapplication.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qeventloop.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsize.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcursor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmargins.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrect.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpalette.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcolor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qrgb.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qregexp.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qbrush.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qregion.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qline.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtransform.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qimage.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfont.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfile.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qguiapplication.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qinputmethod.h \
		SamuLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QKeyEvent \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qicon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QPainter \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainter.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpen.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QFont \
		GameOfLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		SamuBrain.h \
		SamuQl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SamuLife.o: SamuLife.cpp SamuLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QKeyEvent \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qregion.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrect.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsize.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qregexp.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfile.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/QMainWindow \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmargins.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpalette.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcolor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qrgb.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qbrush.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qline.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtransform.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qimage.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfont.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qcursor.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qicon.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QPainter \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpainter.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qtextoption.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/qpen.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtGui/QFont \
		GameOfLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		SamuBrain.h \
		SamuQl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SamuLife.o SamuLife.cpp

GameOfLife.o: GameOfLife.cpp GameOfLife.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		SamuBrain.h \
		SamuQl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameOfLife.o GameOfLife.cpp

SamuBrain.o: SamuBrain.cpp SamuBrain.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QThread \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qthread.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qglobal.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qconfig.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qfeatures.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlogging.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qflags.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtypetraits.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstring.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qchar.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_integrity.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qoldbasicatomic.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_vxworks.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_power.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_alpha.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_bfin.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_s390.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sh4a.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_sparc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlist.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiterator.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qisenum.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/QDebug \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qdebug.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qhash.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpair.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qmap.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qlocale.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvariant.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qvector.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qpoint.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qset.h \
		../Qt5.0.2/5.0.2/gcc_64/include/QtCore/qcontiguouscache.h \
		SamuQl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SamuBrain.o SamuBrain.cpp

moc_GameOfLife.o: moc_GameOfLife.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameOfLife.o moc_GameOfLife.cpp

moc_SamuLife.o: moc_SamuLife.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SamuLife.o moc_SamuLife.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

